<!--
 * @Author: thomas373737
 * @Date: 2022-02-16 19:06:58
 * @LastEditors: thomas373737
 * @LastEditTime: 2022-02-16 19:17:02
 * @FilePath: /GitHub/Full-stack/03、javascript/code/08抛出错误.html
 * @Description: 
 * 
 * Copyright (c) 2022 by 用户/公司名, All Rights Reserved. 
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //throw
      // throw 42;

      // throw {
      //   toString: function () {
      //     return "error";
      //   },
      // };

      //try catch
      // try {
      //   throw new Error("404");
      // } catch (e) {
      //   console.log(e);
      //   console.log(e.stack);
      // }

      function f() {
        try {
          console.log(0);
          throw "bug";
        } catch (e) {
          console.log(1);
          return true; // 这句原本会延迟到 finally 代码块结束再执行
          console.log(2); // 不会运行
        } finally {
          console.log(3);
          return false; // 这句会覆盖掉前面那句 return
          console.log(4); // 不会运行
        }

        console.log(5); // 不会运行
      }

      var result = f();
      // 0
      // 1
      // 3

      result;
      // false
    </script>
  </body>
</html>
